export enum TRANSACTIONS_TYPES {
  RECOVER = "RECOVER",
  DELETE_CONTAINERS = "DELETE_CONTAINERS",
  TRANSFER_REQUEST = "TRANSFER_REQUEST",
  TRANSFER_ACCEPT = "TRANSFER_ACCEPT",
  TRANSFER_REJECT = "TRANSFER_REJECT",
  TRANSFER_CANCEL = "TRANSFER_CANCEL",
  TRANSPORT = "TRANSPORT",
  TRANSPORT_CANCEL = "TRANSPORT_CANCEL",
  TRANSPORT_ACCEPT = "TRANSPORT_ACCEPT",
  TRANSPORT_REJECT = "TRANSPORT_REJECT",
  PROCESS = "PROCESS",
  COMPLETE = "COMPLETE",
}

export enum CONTAINER_STATUS {
  RECOVERED = "RECOVERED",
  DELETED = "DELETED",
  TRANSFER_PENDING = "TRANSFER_PENDING",
  TRANSFER_REJECTED = "TRANSFER_REJECTED", // not neccesary
  TRANSFERRED = "TRANSFERRED",
  IN_TRANSIT = "IN_TRANSIT",
  IN_PROCESS = "IN_PROCESS",
  COMPLETED = "COMPLETED",
}

export enum WASTED_CONTAINER_STATUS {
  PAID = "paid",
  REJECTED = "rejected",
  IN_PROGRESS = "in_progress",
}
